### ISSUE TITLE
Security review

### ISSUE THREAD

**Issue by johnz0r** [PrestaShop/expressmailing#20]
## Sensitive SQL call

/controllers/admin/adminmarketingbuy.php
278 $this->order_session,
279 $this->order_product,
280 $this->media,
281 $this->campaign_id
314 $this->order_session

/controllers/admin/adminmarketingestep1.php
299 $campaign_tracking
300 $campaign_linking
301 $campaign_redlist

/controllers/admin/adminmarketingestep4.php
513 $value

/controllers/admin/db_marketing.php
30 $campaign_id
43 $checked_langs (use array_map + intval)
46 $checked_groups
65 $checked_products
70 $checked_categories
81 $paying_filters['civilities']
84 $paying_filters['countries']
90 $value['country_id'] $value['postcode']
99 $paying_filters['buyingdates']['max_buyingdate']
104 $paying_filters['accountdates']['min_accountdate']
105 $paying_filters['accountdates']['max_accountdate']
119 $value['promocode']
181 190 200 202 214 223 232 241 $campaign_id
254 $filter['birthday_end']
255 $filter['birthday_start']
262 $month_start $month_end
263 $day_start $day_end
266 $filter['birthday_start'] $filter['birthday_end']
284 $campaign_id
298 $checked_langs
300 $checked_groups
311 $checked_products
316 $checked_categories

/controllers/admin/adminmarketingestep5.php
167 $response_array['campaign_id']

/controllers/admin/adminmarketingestep6.php
127 $uploaded_id

/controllers/admin/adminmarketingestep7.php
148 $campaign_last_tester

/controllers/admin/adminmarketingfstep7.php
189 $number_or_email

/controllers/admin/adminmarketingsstep5.php
92 $response_array['campaign_id']

/controllers/admin/adminmarketingsstep6.php
177 $number add pSQL even if 

/controllers/admin/em_tools.php
75 $shop_prefixe
245 $table (use ` + bqSQL)
260 $campaign_id  $number
389 $media
390 $campaign_id
404 $media
409 $campaign_id
## XSS

/views/templates/admin/helpers/tree/tree_node_folder_cat_prod_checkbox.tpl
variables aren't escape, please escape with |escape

/views/templates/admin/marketinge_stats/marketinge_stats.tpl
35 $smarty.get.token

/views/templates/admin/marketinge_step1/marketinge_slider.tpl
15 to 32 replace |escape with |escape:javascript

/views/templates/admin/marketinge_step6/ajax_upload.tpl
15-57 replace |escape with |escape:javascript

/views/templates/admin/marketingf_step1/marketingf_slider.tpl
14-66 replace |escape with |escape:javascript

/views/templates/admin/marketingf_step6/ajax_upload.tpl
15-57 replace |escape with |escape:javascript

/views/templates/admin/marketings_step1/marketings_slider.tpl
15-56 replace |escape with |escape:javascript
### Use of unescape

There are 33 calls to |unescape() in smarty templates, we advise you to remove most of them and replace them with |escape if possible.

It's hard to say if they can lead to XSS without checking them one by one and retracing the path (input, storage in file/DB, processing, assignation to smarty template) of each of them, which will take a to big amount of time for a single module security review.

**Comment by expressmailing** [comment]
Hi @Quetzacoalt91 

There is a last update that we would like to do before the release.
The most important thing is here : 
https://github.com/PrestaShop/expressmailing/blob/master/controllers/admin/adminmarketingx.php#L84
and
https://github.com/PrestaShop/expressmailing/blob/master/controllers/admin/adminmarketingx.php#L325
We need to change the value from "2000" to "400"
We don't have the rights to make a commit anymore 

Thanks

**Comment by Quetzacoalt91** [comment]
The realease has already be done, that's why you cannot commit anymore.

Please create a pull-request with your changes. Do not forget to update your version.
