### ISSUE TITLE
Notices when displaying premium plan

### ISSUE THREAD

**Issue by Quetzacoalt91** [PrestaShop/expressmailing#25]
When I open the popup displaying different Premium Plan, many notices are thrown:
![capture du 2015-05-29 11 30 45](https://cloud.githubusercontent.com/assets/6768917/7880098/d0bb665c-05f6-11e5-9af6-40e3ae4cbea0.png)
![capture du 2015-05-29 11 31 04](https://cloud.githubusercontent.com/assets/6768917/7880099/d492a77c-05f6-11e5-94ff-8bca48e59467.png)

**Comment by expressmailing** [comment]
Hi @Quetzacoalt91 
We have made an update on the API side. Can you make a new try please ?

Thanks

**Comment by Quetzacoalt91** [comment]
Hi @expressmailing,

Really better ! The notices disappeared, thanks !
